### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Fawadkhanfk** [hackerspider1/EchoPwn#11]
Starting subfinder...
./EchoPwn.sh: line 40: ./subfinder: Is a directory

**Comment by Fawadkhanfk** [comment]
atlest create a vedio how to setup and use

**Comment by hackerspider1** [comment]
Please let us know what issue you are facing.
here is step by step instruction how you can setup: https://echopwn.com/road-to-recon-with-echopwn-sh/
