### ISSUE TITLE
cmp() was removed from Python on 1/1/2020

### ISSUE THREAD

**Issue by cclauss** [hackerspider1/EchoPwn#2]
https://github.com/hackerspider1/EchoPwn/blob/master/dirsearch/lib/utils/FileUtils.py#L63-L66

https://portingguide.readthedocs.io/en/latest/comparisons.html#the-cmp-function

**Comment by rooks00** [comment]
Thanks for the heads up. Since dirsearch is maintained by Mauro Soria, we'll be waiting for an update from their side. We have just implemented this tool.
