### ISSUE TITLE
getting error - command not found

### ISSUE THREAD

**Issue by harsh-2519** [hackerspider1/EchoPwn#3]
While running "./EchoPwn.sh domain .com"

Output after giving sub-domain name - 
_______________________________________________
Starting our crtsh script...
Amass turn...
./EchoPwn.sh: line 40: amass: command not found
_______________________________________________

**Comment by rooks00** [comment]
Please share your system details. Also, did you run `install.sh` before running `EchoPwn.sh`?
Check out https://echopwn.com/road-to-recon-with-echopwn-sh/ . This might help clearing some of the issues.

**Comment by hackerspider1** [comment]
We have update the script please have a look. Closing the thread.
