### ISSUE TITLE
aquatone-discover command is not working.

### ISSUE THREAD

**Issue by TesterMoving** [hackerspider1/EchoPwn#8]
I cannot download this tool since the original aquatone command can be run using $aquatone file or cat file | aquatone --chrome-path. Where I can get the source of this ?

I will comment it now from bash script.

**Comment by rooks00** [comment]
aquatone-discover is a separate standalone tool which is used in our script. To install it, you'll need gem in your system. 
`gem install aquatone` 
This command will fix the error you are facing.

**Comment by TesterMoving** [comment]
Hey there, thanks for the support. This can be resolved by adding aquatone using gem. Note that aquatone comes with different binary, and also I find't run the install.sh with sudo. so it is not installed. 

Is there any possibility to add a detailed slack webhook using curl? That would be much better instead of sending just test status.
