### ISSUE TITLE
altdns & massdns should be optional

### ISSUE THREAD

**Issue by attacker34** [hackerspider1/EchoPwn#9]
Hi @hackerspider1 

Great tool as i've seen other ones but its better than others... Just wanna say that please make altdns and massdns functions as optional.Because it takes lot of time which sometime we don't  have and wanna fast forward to other amazing tools in this script. 

Sincerely,

**Comment by hackerspider1** [comment]
Thank you so much for your kind words, valuable feedback we have updated the script now custom brute forcer is optional which was taking long time.
